export const CLOSERS_EP_SLOTS = ["EP_AVATAR_WEAPON", "EP_AVATAR_DEFENCE_HAIR", "EP_AVATAR_DEFENCE_FACE", "EP_AVATAR_DEFENCE_UPBODY", "EP_AVATAR_DEFENCE_LOWBODY", "EP_AVATAR_DEFENCE_HAND", "EP_AVATAR_DEFENCE_FOOT", "EP_AVATAR_ONE_PIECE", "EP_AVATAR_ACC_HEAD_HAIR", "EP_AVATAR_ACC_HEAD_EYE", "EP_AVATAR_ACC_HEAD_EAR", "EP_AVATAR_ACC_HEAD_MOUTH", "EP_AVATAR_ACC_BODY_WING", "EP_AVATAR_ACC_RING_LEFT", "EP_AVATAR_ACC_RING_RIGHT", "EP_AVATAR_ACC_BODY_CHEST", "EP_AVATAR_ACC_HEAD_WAIST", "EP_AVATAR_ACC_LEG"];

export const CLOSERS_EP_SLOTS_MAIN = ["EP_AVATAR_WEAPON", "EP_AVATAR_DEFENCE_HAIR", "EP_AVATAR_DEFENCE_FACE", "EP_AVATAR_DEFENCE_UPBODY", "EP_AVATAR_DEFENCE_LOWBODY", "EP_AVATAR_DEFENCE_HAND", "EP_AVATAR_DEFENCE_FOOT", "EP_AVATAR_ONE_PIECE"];

export const CLOSERS_TEAM_DATA = {
	BLACKLAMBS: {
		name: {
			en: "Black Lambs",
		},
	},
	WOLFDOGS: {
		name: {
			en: "Wolf Dogs",
		},
	},
	WILDHUTER: {
		name: {
			en: "Wildhüter",
		},
	},
	RATTUS: {
		name: {
			en: "Rattus",
		},
	},
};

import CLOSERS_CHARACTER_DATA from "../modules/closers/characters.json";
export { CLOSERS_CHARACTER_DATA };
